### ISSUE TITLE
Typo in second sentence of Chapter 5

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#28]
The second sentence in Chapter 5 is:

In particular, these tools show how the conditional mean of $Y_i$ varies as a function $\mathbf{X}_i$.

This should be:

In particular, these tools show how the conditional mean of $Y_i$ varies as a function of $\mathbf{X}_i$.

(added an "of" near the end)

**Comment by mattblackwell** [comment]
Closed in #58
