### ISSUE TITLE
Typo in third sentence of Chapter 5

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#29]
The third sentence of Chapter 5 is:

For example, we may want to know how wait voting poll wait times vary as a function of some socioeconomic features of the precinct, like income and racial composition.

This should instead be:

For example, we may want to know how voting poll wait times vary as a function of some socioeconomic features of the precinct, like income and racial composition.

(removed an extra "wait" before "voting poll")

**Comment by mattblackwell** [comment]
Fixed by #58
