### ISSUE TITLE
Mistake in first equation below Section 5.2.2 in Chapter 5

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#31]
The first (left) display equation after Section 5.2.2 is:

$m(X_i,X_i^2)=\beta_0+\beta_1 X_i\beta_2 X_i^2$.

This should be replaced with:

$m(X_i,X_i^2)=\beta_0+\beta_1 X_i+\beta_2 X_i^2$.

(added a missing plus sign)

**Comment by mattblackwell** [comment]
Fixed in 13f0ca4
