### ISSUE TITLE
Mistake in first display equation after Section 5.3 of Chapter 5

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#35]
The first display equation after Section 5.3 of Chapter 5 is (using the LaTeX shorcuts you defined in the source code):

$$ 
\mu(\X) = \E[Y_{i} \mid \X_{i}] = \argmin_{g(\X_i) \in L_2}\; \E\left[(Y_{i} - f(\X_{i}))^{2}\right],
$$

This should instead be:

$$ 
\mu(\X) = \E[Y_{i} \mid \X_{i}] = \argmin_{g(\X_i) \in L_2}\; \E\left[(Y_{i} - g(\X_{i}))^{2}\right],
$$

(replaced "f" in the argmin expression with "g" to match the "g" the argmin is being taken over)

**Comment by mattblackwell** [comment]
Thanks!
