### ISSUE TITLE
Grammatical typo in third last paragraph before Section 5.4 of Chapter 5

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#36]
The first sentence of the third last paragraph before Section 5.4 is:

Thus, we can write the CEF with two binary covariates as linear when the linear specification includes and multiplicative interaction between them $(x_1,x_2)$.

This should instead be:

Thus, we can write the CEF with two binary covariates as linear when the linear specification includes a multiplicative interaction between them $(x_1,x_2)$.

(replaced "and" with "a" after "includes")

**Comment by mattblackwell** [comment]
Fixed in 13f0ca4
