### ISSUE TITLE
Mistake in first sentence after first display equation in Section 5.4 of Chapter 5

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#37]
The first sentence after the first display equation in Section 5.4 is:

so that the change in the predicted outcome for increasing $X_{i1}$ by one unit isn’t

Following the logical structure of the argument, this should be:

so that the change in the predicted outcome for increasing $X_{i1}$ by one unit is

(replaced "isn't" with "is")

**Comment by mattblackwell** [comment]
Thanks fixed in 164a636
