### ISSUE TITLE
Slight grammatical error at https://mattblackwell.github.io/gov2002-book/01_intro.html

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#6]
In point #2 on this page, the sentence:

So many methods are either use regression estimators like ordinary least squares or extend it in some way.

should be modified to

So many methods either use regression estimators like ordinary least squares or extend it in some way.

i.e. there's an extra "are" term.

**Comment by mattblackwell** [comment]
Thanks! Closed in https://github.com/mattblackwell/gov2002-book/commit/32e9288831fb154c0607b24b7157e2ad0e750395
