### ISSUE TITLE
Formula 

### ISSUE THREAD

**Issue by evangorstein** [mattblackwell/gov2002-book#62]
Since this is the estimated variance of the stabilized estimator, I think there should be an additional factor of n in the formula from section 7.2?  <img width="262" alt="image" src="https://github.com/mattblackwell/gov2002-book/assets/22649919/e9c309dc-10e0-4934-83c8-aa3b8a6106bd">

**Comment by mattblackwell** [comment]
Awesome, thanks for catching this!
