### ISSUE TITLE
$\hat{\beta}$ should be $\beta$ at start of 7.1

### ISSUE THREAD

**Issue by MattMalis** [mattblackwell/gov2002-book#64]
The second paragraph of 7.1 reads:

> We begin by setting out the assumptions we will need for establishing the large-sample properties of OLS, which are the same as the assumptions needed to ensure that the best linear predictor, $\hat{\beta} = E[X_i X_i']^{-1} E[X_i Y_i]$ , is well-defined and unique.

I believe this should say $\beta$ instead of $\hat{\beta}$

**Comment by mattblackwell** [comment]
Thanks for catching this!
