### ISSUE TITLE
Section 7.3, L'VL not conformable?

### ISSUE THREAD

**Issue by MattMalis** [mattblackwell/gov2002-book#66]
As far as I understand it, L is a (q x k) matrix (q=number of restrictions, k =number of regression coefficients). The expressions $L\beta$ and $L\hat{\beta}$ are used throughout this section, which makes sense. But then presumably $V_\beta$ is a (k x k) covariance matrix. So $L' V_\beta L$ should not be conformable. (The expression appears three times in this section). If instead it were $L V_\beta L'$, this would be conformable.

(Hansen uses $R' V_\beta R$ in the same setting, but in his notation, R is a (k x q) matrix)

**Comment by mattblackwell** [comment]
Thanks for catching this!
