### ISSUE TITLE
Grammatical typo in footnote at https://mattblackwell.github.io/gov2002-book/02_estimation.html#fn1

### ISSUE THREAD

**Issue by Jarell-Cheong** [mattblackwell/gov2002-book#8]
The first sentence of the footnote reads:

This approach to inference is often called a model-based approach since we assuming a probability model in the cdf, $F$.

and should instead be:

This approach to inference is often called a model-based approach since we are assuming a probability model in the cdf, $F$.

(a missing "are" term)

**Comment by mattblackwell** [comment]
Thanks! Closed in https://github.com/mattblackwell/gov2002-book/commit/32e9288831fb154c0607b24b7157e2ad0e750395
